import type { Metadata } from "next";
import Header from '@/src/menu_server.tsx';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <>
            <Header /> 
                {children}
          </>
    );
}
